reviews:
  namespace: prd
  image: ghcr.io/mercurial963/bookinfo-reviews
  tag: prd
  replicas: 1
  imagePullSecrets: ghcr-bookinfo-ratings
  port: 8080
  healthCheckPath: "/health"
  # mongodbPasswordExistingSecret: bookinfo-prd-reviews-mongodb-secret
ingress:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.prd.opsta.co.th
  # path: "/student[X]/reviews(/|$)(.*)"
  serviceType: LoadBalancer
extraEnv:
  SERVICE_VERSION: v2
  # MONGO_DB_URL: mongodb://bookinfo-prd-reviews-mongodb:27017/?authSource=reviews
  # MONGO_DB_NAME: reviews-prd
  # # MONGO_DB_URL: mongodb://bookinfo-prd-reviews-mongodb:27017/reviews-prd
  # MONGO_DB_USERNAME: reviews-prd
  COMMIT_ID: CHANGEME