reviews:
  namespace: uat
  image: ghcr.io/mercurial963/bookinfo-reviews
  tag: uat
  replicas: 1
  imagePullSecrets: ghcr-bookinfo-ratings
  port: 8080
  healthCheckPath: "/health"
  # mongodbPasswordExistingSecret: bookinfo-uat-reviews-mongodb-secret
ingress:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.uat.opsta.co.th
  # path: "/student[X]/reviews(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  # MONGO_DB_URL: mongodb://bookinfo-uat-reviews-mongodb:27017/?authSource=reviews
  # MONGO_DB_NAME: reviews-uat
  # # MONGO_DB_URL: mongodb://bookinfo-uat-reviews-mongodb:27017/reviews-uat
  # MONGO_DB_USERNAME: reviews-uat
  # COMMIT_ID: CHANGEME