reviews:
  namespace: prd
  image: ghcr.io/mercurial963/bookinfo-reviews
  tag: prd
  replicas: 1
  imagePullSecrets: ghcr-bookinfo-ratings
  port: 9080
  healthCheckPath: "/health"
ingress:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.prd.opsta.co.th
  # path: "/student[X]/reviews(/|$)(.*)"
  serviceType: LoadBalancer
extraEnv:
  SERVICE_VERSION: v2
  COMMIT_ID: CHANGEME